spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/eventure
      database: users

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/danilo_eventure
          jwk-set-uri: http://localhost:8080/auth/realms/danilo_eventure/protocol/openid-connect/certs

server:
  port: 8083

logging:
  level:
    org.springframework.security: DEBUG
