version: '3'
services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8080"
    networks:
      - app-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_db:27017/eventure
      - SPRING_DATA_MONGODB_DATABASE=users
      - SPRING_PROFILES_ACTIVE=prod

  event-service:
    build:
      context: ./event-service
    ports:
      - "8082:8080"
    networks:
      - app-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_db:27017/eventure
      - SPRING_DATA_MONGODB_DATABASE=events
      - SPRING_PROFILES_ACTIVE=prod

  participant-service:
    build:
      context: ./participant-service
    ports:
      - "8083:8080"
    networks:
      - app-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_db:27017/eventure
      - SPRING_DATA_MONGODB_DATABASE=participants
      - SPRING_PROFILES_ACTIVE=prod

  task-service:
    build:
      context: ./task-service
    ports:
      - "8084:8080"
    networks:
      - app-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_db:27017/eventure
      - SPRING_DATA_MONGODB_DATABASE=tasks
      - SPRING_PROFILES_ACTIVE=prod

  # MongoDB service shared across all backend services
  mongo_db:
    image: mongo:4.4
    networks:
      - app-network
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
